### ISSUE TITLE
Code review please!

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-sendgrid-event-proxy#1]
Didn't want to waste anyone's time reviewing this until I had it working end-to-end. Now I have:

![Screenshot of fxa-sendgrid-event-proxy in the AWS lambda console](https://user-images.githubusercontent.com/64367/41711177-66e1ccf6-753f-11e8-98e5-113e5410e541.png)

```
~/c/fxa-email-service (pb/queues-sendgrid) $ ./rq
   Compiling fxa_email_service v0.1.0 (file:///Users/pb/code/fxa-email-service)
    Finished dev [unoptimized + debuginfo] target(s) in 17.40s
     Running `target/debug/queues`
{"Logger":"fxa_email_service-0.1.0","Type":"fxa_email_service:log","Pid":47505,"Severity":6,"Timestamp":1529571953912698000,"Fields":{"msg":"Settings::new","settings":"{\"authdb\":{\"baseuri\":\"http://127.0.0.1:8000/\"},\"aws\":{\"keys\":\"[hidden]\",\"region\":\"us-east-1\",\"sqsurls\":{\"bounce\":\"https://sqs.us-east-1.amazonaws.com/927034868273/fxa-email-bounce-dev\",\"complaint\":\"https://sqs.us-east-1.amazonaws.com/927034868273/fxa-email-complaint-dev\",\"delivery\":\"https://sqs.us-east-1.amazonaws.com/927034868273/fxa-email-delivery-dev\",\"notification\":\"https://sqs.us-east-1.amazonaws.com/927034868273/fxa-email-notification-dev\"}},\"bouncelimits\":{\"enabled\":true,\"complaint\":[{\"period\":86400000,\"limit\":0},{\"period\":31536000000,\"limit\":1}],\"hard\":[{\"period\":86400000,\"limit\":0},{\"period\":31536000000,\"limit\":1}],\"soft\":[{\"period\":300000,\"limit\":0}]},\"message_id_hmac_key\":\"YOU MUST CHANGE ME\",\"mozlog\":true,\"provider\":\"ses\",\"redis\":{\"host\":\"127.0.0.1\",\"port\":6379},\"sender\":{\"address\":\"verification@latest.dev.lcip.org\",\"name\":\"Firefox Accounts\"},\"sendgrid\":\"[hidden]\"}"}}
Successfully parsed SQS message, queue=`https://sqs.us-east-1.amazonaws.com/927034868273/fxa-email-delivery-dev`, receipt_handle=`AQEBgaNZUdAKay9nfF4O8szg0IfmegXMcAUUeEXXoBvod0WRUYtYdtJn2dbT870c+tv+kkXheiJXyNnO7d3C+DRiBUgSoiQr33x0kG7m45InPWRz4kPtvRvg07qyfM751ou57yQT3229h5rzGtHcqVphW/+weN7o5gt/rVGW7RK8CWE+y+2rznqT+qbuMg00M2VJ1doZPEDTg3b+s+vHhH3YnSrps0OU+AaRS5sn/wmpFP2Sf4m2k9i7dPuUvDlyO6ytlaLH4NwOCAa1Q5Mf04BtVIp6Hd4Z0Y2uhWjXOATBSC1sy7/J9H2L+DDtI8uFvLDkJoAOIjCZLCmUXBZssiFQbczuy2XuJfu8F2YiSGQh3Blb96dXaORkOqQJIQITL7DWUq6pf2v7BpTRFmn9+f5Qgw==`, notification_type=`Delivery`
Successfully parsed SQS message, queue=`https://sqs.us-east-1.amazonaws.com/927034868273/fxa-email-complaint-dev`, receipt_handle=`AQEBlJxSZFPT/1FpSgXIEIqMXP8RYinu5kWynE8D6n3/rdkM85uxdXgtw00ofYZERZoHGNqvraR+wQiDscPsbTPqDBaVueIvHHX1X092fRTnDQ1zr1cTtYd8LR8H5Ds3JG5PTkSyc4vmF/BFYzJ31TKlIxtpqpVPcMIycxPBOclKt0/20dqjhFGIPb/ufDkCs3/Ohk7NcQnvaxPyiTEuJPxWzkKoaYB4VUgZWJ/dioFb9hFDRQVtEVEKwYoHGGHdTXTSIKTNCimHZlqypWsGYiDCvdrP54sgje0Sp+VH+B+UGKGqiY1+IGVqELuzY2wFOH1wB6V82uQfqKSkySbSMnkdf3EnqLmjw1vsUDGeCigLg+i8EzHJvW2vKLbfWggNY5t29LwFWvuX5VuaHEIUqd/oBg==`, notification_type=`Complaint`
Successfully parsed SQS message, queue=`https://sqs.us-east-1.amazonaws.com/927034868273/fxa-email-bounce-dev`, receipt_handle=`AQEBBSzeVSvyzjxlU43a+PM0fhbCvZC4aKNAPNrMGZHtexjKbyvQlomzdInpgRn/GqAfkqK8oWvLhqVOwIWesd0Xh9LKdbKcZXH4Bk0lLMHVjtJEBrW3HmULIk4gIl/UowUTJvo+DqVz46MIFDoy/xii1+xtkdgs0Wad0I/RXOUoq2I7ahSxDDMIukwTGXDS2OuXMrpjbnguk3cHF8uRwhpJzkH3H2xhkeANHS5WEqBDCE8a+0DW04kMN7dX8SaFGdZotdrvZLyyPyf3wxw9g8KIztfeiPrmTEQRH3iWEhpvxMJl6Cgmj3AlYrc7yJNuL898RaW7Z+ZiNjWIKu79viBQY4SHc0PNHnyLrsm/yG6ABYdrd4wzUAB/+wBtKm+CAWVFn1BG+fehHUC3cbLZsCU63A==`, notification_type=`Bounce`
```

So, belatedly, @mozilla/fxa-devs r? (maybe open issues for anything that you think needs changing)

**Comment by philbooth** [comment]
(I'm writing a readme now sorry, just realised it could do with one of those)

**Comment by rfk** [comment]
Some review comments as I think of them:

* The line with `messageId = event.sg_message_id.split('.filter')[0]` could use a comment explaining the logic behind this parse, maybe an example of expected input and output.
* I don't see anything related to security or credential checking.  Is there a mechanism where we can determine that these events actually came from sendgrid, rather than some rando on the public internet?
* Including ` body: error.stack,` in the error response might not be worth it in production, if we need to debug we should be able to get into from the lambda logs.
* Is there any way that `marshallEvent` could throw, allowing one badly-formatted event to cause us to discard the entire batch?
* Similarly, what happens if `sendEvent` fails due to some sporadic error, do we lose the whole batch, or does sendgrid have some retry facility in the event of our webhook returning a 500 error?

Those musings aside, this looks pretty solid and appropriately lightweight, 👍

**Comment by philbooth** [comment]
> I don't see anything related to security or credential checking. Is there a mechanism where we can determine that these events actually came from sendgrid, rather than some rando on the public internet?

There is not. I was looking for such a thing in the [docs](https://sendgrid.com/docs/API_Reference/Event_Webhook/event.html), but didn't see a way to do it. Are you aware of something I missed?

**Comment by philbooth** [comment]
> Including ` body: error.stack,` in the error response might not be worth it in production, if we need to debug we should be able to get into from the lambda logs.

It's probably because I'm an AWS novice, but I couldn't get the Lambda logs to work. I click on "Monitoring" then on "Jump to logs" and I get this error:

![Error: "Log group not found"](https://user-images.githubusercontent.com/64367/41763593-857c69c0-75f6-11e8-934f-852e8ea3bcd5.png)

I guess there is something else I need to configure here for them to show up? Or maybe I'm supposed to use something other than `console.log` in the code? (sorry, these aren't really questions for you, I'll go and RTFM)

**Comment by philbooth** [comment]
> > I don't see anything related to security or credential checking. Is there a mechanism where we can determine that these events actually came from sendgrid, rather than some rando on the public internet?
>
> There is not. I was looking for such a thing in the [docs](https://sendgrid.com/docs/API_Reference/Event_Webhook/event.html), but didn't see a way to do it. Are you aware of something I missed?

Never mind, I found the answer on SO. It's kind of obvious in hindsight, either you use basic auth in the webhook URL or you add a query string and check the value matches whatever.

**Comment by philbooth** [comment]
> It's probably because I'm an AWS novice, but I couldn't get the Lambda logs to work.

Again, obvious in hindsight. "Create log group".

Sorry, I'm not trying very hard this morning. 😄

**Comment by philbooth** [comment]
> ...what happens if `sendEvent` fails due to some sporadic error, do we lose the whole batch, or does sendgrid have some retry facility in the event of our webhook returning a 500 error?

It retries with exponential backoff for up to 24 hours, then fails permanently. I think I read somewhere that it's possible to configure a fallback notification mechanism for the permanent failure case, but I can't see anything about it in the docs now and I can't find it in settings. Maybe I imagined that part.

**Comment by philbooth** [comment]
> The line with `messageId = event.sg_message_id.split('.filter')[0]` could use a comment explaining the logic behind this parse, maybe an example of expected input and output.

Done.

> I don't see anything related to security or credential checking.  Is there a mechanism where we can determine that these events actually came from sendgrid, rather than some rando on the public internet?

Done, via an `auth` query param.

> Including ` body: error.stack,` in the error response might not be worth it in production, if we need to debug we should be able to get into from the lambda logs.

Done.

> Is there any way that `marshallEvent` could throw, allowing one badly-formatted event to cause us to discard the entire batch?

There was, but I've made it more robust now. Malformed error objects are now discarded so that the remainder of the batch can be processed without hitches.

**Comment by philbooth** [comment]
> ...what happens if `sendEvent` fails due to some sporadic error, do we lose the whole batch, or does sendgrid have some retry facility in the event of our webhook returning a 500 error?

Hopefully if we keep the lambda function in the same AWS region as the SQS queues, the probability of independent failure is low enough to be acceptable?

**Comment by rfk** [comment]
> either you use basic auth in the webhook URL or you add a query string and check the value matches whatever.

Aha, nice, that WMF!  Basically "treat the URL itself as a secret".

**Comment by philbooth** [comment]
This seems done so closing it out, but of course further comments are welcome if anyone has them (open an issue).
