### ISSUE TITLE
Tag a new release to pick up current master, including fix with aws-sdk

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-sendgrid-event-proxy#14]
It would be good to get a tag on current master, with the fix for aws-sdk.

**Comment by philbooth** [comment]
https://github.com/mozilla/fxa-email-event-proxy/releases/tag/v1.126.0

**Comment by philbooth** [comment]
https://18-138079385-gh.circle-artifacts.com/0/home/circleci/fxa-email-event-proxy/artifacts/fxa-email-event-proxy.v1.126.0.zip

**Comment by jrgm** [comment]
Thanks. But I just bumped into something that will need a code change, which I'll file an issue on now.
