### ISSUE TITLE
Deploy email-event-proxy in prod

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-sendgrid-event-proxy#6]
So that we can have metrics working from SocketLabs/Sendgrid.

**Comment by philbooth** [comment]
We might get this done ahead of schedule, in train 121. Tentatively moving it into `active`.

**Comment by philbooth** [comment]
Punting this to 122.

**Comment by philbooth** [comment]
This is archive for uploading to Lambda:

https://17-138079385-gh.circle-artifacts.com/0/home/circleci/fxa-email-event-proxy/artifacts/fxa-email-event-proxy.v1.121.2.zip

**Comment by philbooth** [comment]
Pulled across to `active` to be done as part of the train 125 deployment cycle. Note this is an ops task, so there's no need to freak out about the fact I'm on PTO and my face is on this.

**Comment by vladikoff** [comment]
from mtg: seems like the module we use does not support AWS Policies, but @jrgm has a rewrite that supports this feature.

**Comment by vladikoff** [comment]
from mtg: waiting for @jbuck to r+

**Comment by jrgm** [comment]
Closing. This has been live in production since 12/11
